<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mmenu extends CI_Model
{

    public $table = 'menu';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('kategori_id', $q);
        $this->db->or_like('kode_menu', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        //join tabel dengan kategori
        $this->db->select('b.*, k.nama_kategori');
        $this->db->from('menu b');
        $this->db->join('kategori k', 'k.id=b.kategori_id');

        $this->db->order_by('b.id', $this->order);
        $this->db->like('b.id', $q);
        $this->db->or_like('b.nama', $q);
        $this->db->or_like('b.harga', $q);
        $this->db->or_like('b.kode_menu', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function get_count()
    {
        $sql = "SELECT count(id) as id FROM menu";
        $result = $this->db->query($sql);
        return $result->row()->id;
    }
}

/* End of file Mmenu.php */
/* Location: ./application/models/Mmenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-23 16:29:13 */
/* http://harviacode.com */