<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MUser extends CI_Model
{

    public $table = 'user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('nama_lengkap', $q);
        $this->db->or_like('hak_akses', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('nama_lengkap', $q);
        $this->db->or_like('hak_akses', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function CheckUser($username, $password)
    {
        $query = $this->db->get_where(
            $this->table,
            array(
                'username' => $username,
                'password' => $password
            )
        );

        if ($query->num_rows() > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function get_count()
    {
        $sql = "SELECT count(id) as id FROM user";
        $result = $this->db->query($sql);
        return $result->row()->id;
    }

    function get_all_by_username($username)
    {
        $this->db->where('username', $username);
        return $this->db->get($this->table)->row();
    }
    function get_all()
    {
        $this->db->order_by('nama_lengkap', 'ASC');
        return $this->db->get($this->table)->result();
    }
}

/* End of file MUser.php */
/* Location: ./application/models/MUser.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-24 09:36:25 */
/* http://harviacode.com */